name: BuTils
main: wex\BuTils\BuTils
version: 0.0.2
api: 5.25.0
author: Wex
description: A build utility plugin that makes life easier for builders.
website: https://github.com/Xeww/BuTils

permissions:
  butils.command.butils:
    default: op

  butils.command.flyspeed:
    default: op

  butils.command.noclip:
    default: op

  butils.command.nightvision:
    default: op
